# tmux 256 colors
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set-option -sa terminal-overrides 'xterm-256color:RGB'

#マウス操作を有効にする
set-option -g mouse on

# ウィンドウのインデックスを1から始める
set -g base-index 1
# ペインのインデックスを1から始める
setw -g pane-base-index 1

## status line の背景色を指定する。
set-option -g status-bg "colour238"
## status line の文字色を指定する。
set-option -g status-fg "colour255"

# スクロールバッファ
set -g history-limit 5000

# 現在のウィンドウの色
set -g pane-active-border-style fg="blue"

# コピーモードのキー操作をviライクにする
set-window-option -g mode-keys vi

# windowの入れ替え
bind -r '{' swap-window -d -t -1
bind -r '}' swap-window -d -t +1

