# tmux 256 colors
set -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set -sa terminal-overrides 'xterm-256color:RGB'

#マウス操作を有効にする
set -g mouse on

# ウィンドウのインデックスを1から始める
set -g base-index 1
# ペインのインデックスを1から始める
setw -g pane-base-index 1

# ウィンドウを閉じた時に番号を詰める
set -g renumber-windows on

# ウィンドウ履歴の最大行数
set -g history-limit 50000

## status line の背景色を指定する。
set -g status-bg "colour238"
## status line の文字色を指定する。
set -g status-fg "colour255"

# 現在のウィンドウの色
set -g pane-active-border-style fg="blue"

# コピーモードのキー操作をviライクにする
setw -g mode-keys vi

# 設定ファイルをリロード(Prefix + r)
bind-key -T prefix r source-file ~/.tmux.conf \; display-message 'Reloard was successful.'

# windowの入れ替えを`{`, `}`で行う
bind -r '{' swap-window -d -t -1
bind -r '}' swap-window -d -t +1

# ペインの移動をvim風にする
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインのリサイズをvi風にする(Prefix -> ctrl +	h/j/k/l)
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10
