model = "gpt-5-codex"

model_reasoning_effort= "medium"

file_opener = "cursor"

[tui]
#　デスクトップ通知に関する設定
# - "agent-turn-complete": エージェントの１ターン処理が完了した際に通知
# - "approval-requested": ユーザーの操作や承認が必要な時に通知
notifications = ["agent-turn-complete","approval-requested"]
