[tools]
neovim = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
bun = "latest"
rust = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:sharkdp/bat" = "latest"
eza = "latest"
"aqua:sharkdp/fd" = "latest"
gh = "latest"
lazygit = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
pipx.uvx = true
