[tools]
# ruby = "latest"
go = "latest"
node = "latest"
rust = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"aqua:aws/aws-cli" = "latest"
eza = "latest"

[settings]
idiomatic_version_file_enable_tools = []
pipx.uvx = true
