[bootstrap.packages]
"brew:coreutils" = "latest"
"brew:curl" = "latest"
"brew:ffmpeg" = "latest"
"brew:git" = "latest"
"brew:gitleaks" = "latest"
"brew:htop" = "latest"
"brew:librsvg" = "latest"
"brew:llvm" = "latest"
"brew:mactop" = "latest"
"brew:mcat" = "latest"
"brew:mysql" = "latest"
"brew:ninja" = "latest"
"brew:resvg" = "latest"
"brew:subversion" = "latest"
"brew:swiftlint" = "latest"
"brew:tex-fmt" = "latest"
"brew:tree" = "latest"
"brew:wget" = "latest"
# For macOS

