[tools]
# lang
go = "latest"
node = "lts"
rust = "latest"
# package manager
bun = "latest"
pnpm = "latest"
# cli
delta = "latest"
eza = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"
zoxide = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"github:d-kuro/gwq" = "latest"
# tool
neovim = "latest"
tree-sitter = "latest"
starship = "latest"
git-lfs = "latest"
# ai
gemini-cli = "latest"
codex = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
opencode = "latest"

[settings]
idiomatic_version_file_enable_tools = []
pipx.uvx = true
npm.package_manager = "bun"

