[tools]
# lang
go = "latest"
node = "lts"
rust = "latest"
# package manager
bun = "latest"
pnpm = "latest"
# cli
delta = "latest"
eza = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"
zoxide = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"github:d-kuro/gwq" = "latest"
# tool
neovim = "latest"
tree-sitter = "latest"
starship = "latest"
git-lfs = "latest"
# ai
gemini-cli = "latest"
codex = "latest"
opencode = "latest"
claude-code = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }

[settings]
idiomatic_version_file_enable_tools = []
pipx.uvx = true
npm.package_manager = "bun"
