[mgr]
sort_dir_first = true

[plugin]
preloaders = []
previewers = []

[[plugin.prepend_fetchers]]
id = "mime"
url = "local://*"
run = "mime-ext.local"
prio = "high"

[[plugin.prepend_fetchers]]
id = "mime"
url = "remote://*"
run = "mime-ext.remote"
prio = "high"
