[tools]
# lang
go = "latest"
node = "latest"
rust = "latest"
# package manager
bun = "latest"
pnpm = "latest"
# tool
eza = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"github:d-kuro/gwq" = "latest"
tree-sitter = "latest"
starship = "latest"

[settings]
idiomatic_version_file_enable_tools = []
pipx.uvx = true
